// All user-visible strings in English.
// To add a locale, create a parallel object with the same shape and swap T at app init.

export const T = {

  // ── Shared ─────────────────────────────────────────────────────────────────
  common: {
    cancel:     'Cancel',
    back:       '← Back',
    ok:         'OK',
    add:        'Add',
    remove:     'Remove',
    delete:     'Delete',
    unlock:     'Unlock',
    none:       'None',
    vip:        'VIP',
    processing: 'Processing…',
    guests:     (n: number) => n === 1 ? '1 guest' : `${n} guests`,
    nMin:       (n: number) => `${n} min`,
    covers:     'covers',
  },

  // ── Reservation status labels ───────────────────────────────────────────────
  reservationStatus: {
    PENDING:   'Pending',
    CONFIRMED: 'Confirmed',
    SEATED:    'Seated',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    NO_SHOW:   'No-show',
  } as Record<string, string>,

  // ── Live table status labels ────────────────────────────────────────────────
  tableStatus: {
    AVAILABLE:     'Available',
    OCCUPIED:      'Seated',
    RESERVED_SOON: 'Arriving soon',
    RESERVED:      'Reserved',
    BLOCKED:       'Blocked',
  } as Record<string, string>,

  // ── TopBar ─────────────────────────────────────────────────────────────────
  topBar: {
    brand:          'Iron Booking',
    zoomTitle:      'Zoom — click percentage to reset to 100%',
    zoomOut:        'Zoom out',
    zoomIn:         'Zoom in',
    resetZoom:      'Reset to 100%',
    switchToLight:  'Switch to light mode',
    switchToDark:   'Switch to dark mode',
    signOut:        'Sign out',
    prevDay:        'Previous day',
    nextDay:        'Next day',
    prev30:         '−30m',
    next30:         '+30m',
    nowBtn:         'Now',
    backToToday:    'Back to today',
    guestsButton:   'Guests',
    adminButton:    'Admin',
    activeHost:          (name: string) => `Active Host: ${name}`,
    switchHost:          'Switch Host',
    bulkConfirmButton:   'Confirmations',
    sseReconnecting:     'Reconnecting…',
    sseOffline:          'Live updates offline',
  },

  // ── FloorBoard ─────────────────────────────────────────────────────────────
  floorBoard: {
    reconnecting:     'Reconnecting to server…',
    reconnectingHint: 'This may take a few seconds',
    errorTitle:       'Cannot reach server',
    errorHint:        'Try refreshing if this persists.',
    errorRetry:       'Dashboard will retry automatically.',
    emptyTitle:       'No tables configured',
    emptyHint:        'Add tables via the admin panel, then refresh.',
    statAvailable:    'Available',
    statSeated:       'Seated',
    statArriving:     'Arriving',
    statFreeing:      'Freeing',
    statReserved:     'Reserved',
    tableCount:       (n: number) => `${n} tables`,
    lockedTitle:      (name: string) => `${name} is locked`,
    unlockTable:      'Unlock table',
    lockTable:        'Lock table…',
    seatAnyway:       'Seat walk-in anyway',
    ending:           'Ending',
    mLeft:            (n: number) => `${n}m left`,
    mOver:            (n: number) => `+${n}m over`,
    inNMin:           (n: number) => `in ${n}m`,
    viewFloor:        'Floor',
    viewTimeline:     'Timeline',
    sectionOther:     'Other',
    combineHint:      'Tap available tables to combine',
    combineCreate:    'Create Combined Reservation',
    pickModeHint:             'Click or drag to select tables',
    pickModeSelected:         (n: number) => n === 1 ? '1 table' : `${n} tables`,
    pickModeConfirm:          'Confirm',
    pickModeCancel:           'Cancel',
    pickModeUnavailable:      (name: string) => `${name} is not available for this time slot`,
    pickModeMoveHint:         (name: string) => `Choose a new table for ${name}`,
    pickModeCurrentTable:     'Current table',
    pickModeCurrentTableWarn: 'That\'s the current table — choose a different one',
    reorganizeBanner: 'Reorganize Mode — click any table to lift its upcoming reservations to the queue',
    zoomOut:   'Zoom out  (Ctrl −)',
    zoomIn:    'Zoom in  (Ctrl +)',
    zoomReset: 'Reset zoom to 100%',
    soon:      'Soon',
  },

  // ── TableTimeline ──────────────────────────────────────────────────────────
  tableTimeline: {
    headerTable:  'Table',
    legendSoon:   'Soon',
    legendConf:   'Conf',
    legendSeat:   'Seat',
    legendDone:   'Done',
    gapPerfect:   'Perfect slot',
    gapTight:     'Tight fit',
    gapShort:     'Short window',
    endingNow:    'Ending now',
    endsMin:      (n: number) => `Ends ${n}m`,
    nextMin:      (n: number) => `Next ${n}m`,
    mWait:        (n: number) => `${n}m wait`,
    seatAction:   '→ Seat',
    addAction:    '+ Add',
    seatGuest:    (name: string, size: number) => `Seat ${name} (${size})`,
    fitsCovers:   (min: number, max: number) => `Fits ${min}–${max}`,
    actionSeat:   'Seat',
    actionMove:   'Move',
    actionCancel: 'Cancel',
  },

  // ── TableCard ──────────────────────────────────────────────────────────────
  tableCard: {
    covers:          'covers',
    clickToSeat:     'Click to seat a walk-in',
    openTapToSeat:   'Open · tap to seat walk-in',
    endsIn:          (n: number) => `Ends in ${n}m`,
    endsNow:         'Ends now',
    overBy:          (n: number) => `Over by ${n}m`,
    lateBy:          (n: number) => `${n}m late`,
    inNMin:          (n: number) => `in ${n}m`,
    waitlistWaiting: (n: number) => `Waitlist · ${n}m waiting`,
    locked:          'Locked',
  },

  // ── ActionBar ──────────────────────────────────────────────────────────────
  actionBar: {
    now: 'Now',
    sectionUnderPressure: (name: string) => `${name} · Under pressure`,
    sectionFillingUp:     (name: string) => `${name} · Filling up`,
    pacingEasing:     'Floor · Easing',
    pacingTightening: 'Floor · Tightening',
  },

  // ── Arrival states ─────────────────────────────────────────────────────────
  arrival: {
    arrivingSoon:  'Arriving soon',
    dueNow:        'Due now',
    lateMin:       (n: number) => `${n}m late`,
    noShowRisk:    'No-show risk',
    insightLate:   (name: string, n: number) => `${name} is ${n}m late`,
    insightNoShow: (name: string, n: number) => `${name} — no-show risk (${n}m)`,
  },

  // ── ReservationPanel ───────────────────────────────────────────────────────
  reservationPanel: {
    tabReservations:  'Reservations',
    tabWaitlist:      'Waitlist',
    walkIn:           'Walk-in',
    newReservation:   '+ New',
    searchPlaceholder:'Search name or phone…',
    filterActive:     'Active',
    filterSeated:     'Seated',
    filterDone:       'Done',
    filterNoTable:    'No Table',
    noTableBadge:     'No table',
    chooseTable:      'Choose Table',
    emptyTitle:       'No reservations today',
    emptyHintNew:     '+ New',
    emptyHintWalkIn:  'Walk-in',
    emptyHint:        'Use {new} for a phone booking or {walkIn} for guests at the door.',
    emptyFiltered:    'No reservations match this filter',
    showing:          (visible: number, total: number) => `Showing ${visible} of ${total}`,
    emptyHintPrefix:  'Use ',
    emptyHintMid:     ' for a phone booking or ',
    emptyHintSuffix:  ' for guests at the door.',
    needsReminder:    'Needs reminder',
    noPhone:          'No phone',
    confirmedTick:    '✓ Arrival confirmed',
    runningLate:      'running late',
    arrivedBadge:     'arrived',
    reminded:         'reminded',
    smsSent:          'SMS sent',
    ctxSeat:          'Seat',
    ctxClose:         'Close',
    reorganizeHeader: (n: number) => `Reorganize · ${n}`,
    reorganizeRemovedFrom: (table: string) => `Removed from ${table}`,
    reorganizeAssign:    'Assign table',
    reorganizeOpen:      'Open',
  },

  // ── Waitlist assign mode ───────────────────────────────────────────────────
  waitlistAssign: {
    chooseBanner:  (name: string, party: number) => `Choose a table for ${name} (${party}p)`,
    confirmSeat:   (name: string, table: string) => `Seat ${name} at ${table}`,
    noTableSeat:   (name: string) => `Seat ${name} (no table)`,
    cancelAssign:  'Cancel',
    seatNow:       'Seat Now',
  },

  // ── WaitlistPanel ──────────────────────────────────────────────────────────
  waitlistPanel: {
    readyToSeat:      'Ready to seat',
    seatButton:       'Seat',
    seatFutureDisabled: 'This reservation belongs to another service date and cannot be seated today.',
    namePlaceholder:  'Guest name *',
    partyPlaceholder: 'Party *',
    phonePlaceholder: 'Phone (optional)',
    addButton:        'Add to waitlist',
    addBusy:          'Adding…',
    addLink:          '+ Add guest to waitlist',
    emptyTitle:       'Waitlist is empty',
    emptyHint:        'Add guests above when all tables are occupied.',
    notifyButton:     'Notify',
    notifiedJustNow:  'Notified just now',
    notifiedAgo:      (n: number) => `Notified ${n}m ago`,
    noShow:           'No-show',
    cancelButton:     'Cancel',
    footerEmpty:      'No one waiting',
    footerCount:      (n: number) => `${n} waiting`,
    mWaiting:         (n: number) => `${n}m waiting`,
    guests:           (n: number) => `${n} guests`,
    tableLabel:       (name: string) => `Table ${name}`,
    etaReady:         'Ready now',
    etaMin:           (n: number) => `ETA ${n}m`,
    waitingMin:       (n: number) => `waiting ${n}m`,
    justAdded:        'Just added',
  },

  // ── CreateDrawer ───────────────────────────────────────────────────────────
  createDrawer: {
    titleReservation:     'New Reservation',
    titleWalkIn:          'Walk-in',
    tabReservation:       'Reservation',
    tabWalkIn:            'Walk-in',
    // Reservation form
    fieldGuestName:       'Guest name *',
    fieldPhone:           'Phone',
    fieldPartySize:       'Party size *',
    fieldDate:            'Date *',
    fieldTime:            'Time *',
    fieldDuration:        'Duration (min)',
    fieldSource:          'Source',
    fieldGuestNotes:      'Guest notes',
    fieldHostNotes:       'Host notes',
    fieldTable:              'Table',
    placeholderName:         'Full name',
    placeholderPhone:        '+1 555 000 0000',
    placeholderDuration:     '90',
    durationPreset90:        '90 min',
    durationPreset120:       '120 min',
    placeholderGuestNotes:   'Allergies, special requests…',
    placeholderHostNotes:    'Internal notes for the team…',
    sourcePhone:             'Phone',
    sourceInternal:          'Internal',
    submitCreate:            'Create & Confirm',
    submitCreateBusy:        'Creating…',
    tableNone:               'None',
    // Auto-allocation UI
    autoLabel:               'Auto',
    tableSearching:          'Finding best table…',
    tableAutoSelected:       (name: string) => `Table ${name}`,
    tableAutoCombined:       (names: string) => `Tables ${names}`,
    tableNoAvailable:        'No available table for this slot',
    tableShowAll:            'Show all tables',
    tableChangeBtn:          'Change table',
    tableClearSelection:     'Clear selection',
    tableSelectOnMap:        'Select on map',
    tablePickingOnMap:       'Selecting on map…',
    tableCapacityWarn:       (cap: number, party: number) => `Selected table capacity is ${cap}, reservation size is ${party}`,
    tableUseAuto:            '← Use suggested',
    confirmWithTable:        (name: string) => `Confirm Reservation – Table ${name}`,
    confirmWithTables:       (names: string) => `Confirm Reservation – Tables ${names}`,
    confirmNoTable:          'Confirm – No Table Assigned',
    confirmChecking:         'Checking tables…',
    // Walk-in form
    fieldWalkInName:      'Guest name',
    fieldWalkInPhone:     'Phone',
    placeholderWalkInPhone: 'Optional — for repeat guest lookup',
    fieldWalkInParty:     'Party size *',
    fieldWalkInDuration:  'Seating duration (min)',
    durationPreset60:     '60 min',
    durationPreset150:    '150 min',
    walkInEndsAt:         (time: string) => `Ends ~${time}`,
    fieldWalkInNotes:     'Notes',
    fieldWalkInTable:     'Table (select to seat immediately)',
    placeholderWalkInName:"Optional — defaults to 'Walk-in Guest'",
    placeholderWalkInNotes:'Allergies, occasion, preferences…',
    walkInTableSelected:  (name: string) => `Table ${name} selected — guest will be seated immediately.`,
    walkInNoTable:        'No table selected — guest will be added to the confirmed list.',
    submitSeatNow:        'Seat Now',
    submitSeatNowBusy:    'Seating…',
    submitAddToList:      'Add to List',
    submitAddToListBusy:  'Adding…',
    // Phone warning
    phoneWarnTitle:       'No phone number entered',
    phoneWarnBody:        'Without a phone number you won\'t be able to send confirmations, reminders, or contact this guest if they\'re late.',
    phoneWarnAddPhone:    'Go Back and Add Phone',
    phoneWarnContinue:    'Continue Without Phone',
  },

  // ── Table picker ───────────────────────────────────────────────────────────
  tablePicker: {
    statusBadge: {
      recommended: 'Recommended',
      possible:    'Possible',
      tight:       'Tight',
      blocked:     'Blocked',
    } as Record<string, string>,
    reasonText: (r: import('./types').ScoredReason): string => {
      switch (r.code) {
        case 'CONFLICT':         return r.at ? `Conflicts with booking at ${r.at}` : 'Conflicts with existing booking';
        case 'TOO_SMALL':        return 'Table too small for party';
        case 'TABLE_BLOCKED':    return 'Table is blocked';
        case 'PERFECT_FIT':      return 'Perfect capacity fit';
        case 'GOOD_FIT':         return 'Good capacity fit';
        case 'LARGE_TABLE':      return `Table too large for ${r.partySize} guests`;
        case 'GAP_BEFORE_TIGHT': return `Tight gap — prev booking at ${r.prevTime}`;
        case 'GAP_AFTER_TIGHT':  return `Tight gap — next booking at ${r.nextTime}`;
        case 'GAP_BEFORE_WARN':  return `Short gap before booking at ${r.prevTime}`;
        case 'GAP_AFTER_WARN':   return `Short gap before next booking at ${r.nextTime}`;
      }
    },
  },

  // ── GuestDrawer ────────────────────────────────────────────────────────────
  guestDrawer: {
    editButton:           'Edit',
    // Reservation detail rows
    rowDate:              'Date',
    rowTime:              'Time',
    rowSeatedAt:          'Seated at',
    seatFutureDisabled:   'This reservation belongs to another service date and cannot be seated today.',
    rowDuration:          'Duration',
    rowTable:             'Table',
    rowSource:            'Source',
    rowOccasion:          'Occasion',
    rowGuestNotes:        'Guest notes',
    rowHostNotes:         'Host notes',
    tableUnassigned:      'Unassigned',
    durationValue:        (n: number) => `${n} min`,
    // Guest profile
    sectionGuestProfile:  'Guest profile',
    rowName:              'Name',
    rowVisits:            'Visits',
    rowNoShows:           'No-shows',
    // Actions
    sectionActions:       'Actions',
    actionConfirm:        'Confirm',
    actionMarkArrived:    'Mark arrived',
    actionSeat:           'Seat',
    actionNoShow:         'No-show',
    actionCancel:         'Cancel',
    actionComplete:       'Complete',
    actionMoveTable:      'Move table',
    actionUnseat:         'Return to List',
    unseatConfirmText:    'This will remove the guest from the table and return the reservation to the list. Continue?',
    returnedToList:       'Returned to List',
    actionUnconfirm:      'Revert to pending',
    actionChooseTable:       'Choose table',
    actionChangeTable:       'Change table',
    actionChangeCombination: 'Change combination',
    actionUndoArrival:       'Undo arrival',
    actionSendSms:        'Send SMS',
    actionUndo:           'Undo',
    // Edit mode fields
    fieldGuestName:       'Guest name',
    fieldPhone:           'Phone',
    fieldDate:            'Date',
    fieldTime:            'Time',
    fieldPartySize:       'Party size',
    fieldDuration:        'Duration',
    fieldGuestNotes:      'Guest notes',
    fieldHostNotes:       'Host notes',
    placeholderName:      'Full name',
    placeholderPhone:     '+1 555 000 0000',
    placeholderNotes:     'Allergies, preferences…',
    placeholderHostNotes: 'Internal notes…',
    placeholderMinutes:   'Minutes',
    wasNMin:              (n: number) => `was ${n}m`,
    saveChanges:          'Save changes',
    seatedEditNote:       'Reservation is seated — date, time, and table are locked. Guest count and other details can still be updated.',
    tableConflictNote:    'Changing time or party size will re-validate the current table assignment.',
    fieldTable:           'Table',
    changeTable:          'Change',
    clearTable:           'Clear',
    selectOnMap:          'Select on map',
    pickingOnMap:         'Selecting on map…',
    tableCapacityWarn:    (cap: number, party: number) => `Selected table capacity is ${cap}, reservation size is ${party}`,
    suggestedTablesLabel: 'Suggested',
    allTablesLabel:       'All tables',
    sectionTableUpcoming: (name: string) => `Also booked at ${name}`,
    // Seat / move pickers
    seatPickerLabel:         'Select a table to seat:',
    movePickerLabel:         'Move to table:',
    changeTablePickerLabel:  'Assign a different table:',
    noTablesAvailable:    'No tables available',
    backLink:             '← Back',
    // Cancel mode
    cancelReasonLabel:    'Reason (optional):',
    cancelReasonPh:       'Guest request, weather…',
    confirmCancel:        'Confirm cancel',
    backButton:           'Back',
    // Delete mode
    deleteConfirmLabel:   'This will permanently delete the reservation. This cannot be undone.',
    confirmDelete:        'Yes, permanently delete',
    toastDeleted:         'Reservation deleted',
    // Table lock section
    sectionTableLock:     'Table lock',
    unlockButton:         'Unlock',
    lockTableButton:      'Lock table…',
    lockTableBusy:        'Locking…',
    lockTableConfirm:     'Lock table',
    lockReasonPh:         'Custom reason (optional)',
    quickLockReasons:     ['VIP', 'Broken', 'Staff', 'Reserved', 'Other'] as const,
    // Timeline section
    sectionTimeline:      'Timeline',
    timelineEmpty:        'No lifecycle events yet',
    tsConfirmed:          'Confirmed',
    tsSeated:             'Seated',
    tsCompleted:          'Completed',
    tsCancelled:          'Cancelled',
    tsNoShow:             'No-show',
    // Attribution
    attrCreatedBy:        'Created by',
    attrUpdatedBy:        'Updated by',
    attrSeatedBy:         'Seated by',
    attrCancelledBy:      'Closed by',
    attrMovedBy:          'Moved by',
    // Toasts
    toastUpdated:         'Reservation updated',
    toastConfirmed:       'Reservation confirmed',
    toastUnconfirmed:     'Reverted to pending',
    toastNoShow:          'Marked as no-show',
    toastArrived:         'Guest marked as arrived',
    toastCompleted:       'Reservation completed',
    toastUnseated:        'Guest returned to list',
    toastUndone:          'Action undone',
    toastTableAssigned:   (table: string) => `Table ${table} assigned`,
    toastSeated:          (table: string) => `Seated at ${table}`,
    toastMoved:           (table: string) => `Moved to ${table}`,
    toastLocked:          (name: string) => `${name} locked`,
    toastUnlocked:        (name: string) => `${name} unlocked`,
    // Reorganize
    reorganizeBadge:      'Reorganize',
    reorganizeModalTitle: 'Table has upcoming reservations',
    reorganizeModalBody:  (n: number) => `This table has ${n === 1 ? '1 upcoming reservation' : `${n} upcoming reservations`}. Seating here will move them to the Reorganize queue so you can assign them new tables.`,
    reorganizeModalGuest: (name: string, time: string, party: number) => `${name} · ${time} · ${party}p`,
    reorganizeModalEta:   (n: number) => n <= 0 ? 'now' : `in ${n}m`,
    reorganizeConfirm:    'Seat & Reorganize',
    // Fallback error
    actionFailed:         'Action failed',
    // Confirmation section
    confirmationSection:  'Confirmation',
    guestArrived:         'Arrived — waiting at entrance',
    guestRunningLate:     'Guest running late',
    guestConfirmed:       'Arrival confirmed',
    runningLate:          'Running late',
    smsSentBadge:         'SMS sent',
    viaSms:               'via SMS',
    needsReminder:        'Needs reminder',
    smsSentAwaiting:      (time: string) => `SMS sent ${time} · awaiting reply`,
    noConfirmationSent:   'No confirmation sent yet',
    reminderSentAt:       'Reminder sent',
    maxRemindersReached:  'max reached',
    sendConfirmation:     'Send confirmation SMS',
    resendConfirmation:   'Resend confirmation',
    confirmationSent:     'Confirmation SMS sent',
    confirmationResent:   'Confirmation SMS resent',
    sendReminderNow:      'Send reminder now',
    sendReminder:         'Send reminder',
    reminderSentToast:    'Reminder sent',
    noPhone:              'No phone available',
    markAsConfirmed:      'Mark as confirmed',
    markedAsConfirmed:    'Marked as confirmed',
    sourceLabels:         { Phone: 'Phone', Internal: 'Internal', 'Walk-in': 'Walk-in', Online: 'Online', System: 'System' } as Record<string, string>,
    // Smart suggestion
    sectionSmartSuggest:       'Suggested Table',
    sectionSmartUpgrade:       'Better Table Available',
    suggestSeatNow:            'Seat Now',
    suggestChooseOther:        'Choose another table',
    suggestSwapTable:          'Move to this table',
    suggestKeepCurrent:        'Keep current',
    suggestCurrentLabel:       'Current',
    suggestBetterLabel:        'Suggested',
    suggestReasonPerfectFit:   'Perfect fit',
    suggestReasonAvailable:    'Available now',
    suggestReasonNoConflicts:  'No conflicts',
    suggestCapacity:           (min: number, max: number) => `${min}–${max} guests`,
    toastTableReassigned:      (table: string) => `Table changed to ${table}`,
  },

  // ── TableQuickPanel ────────────────────────────────────────────────────────
  tableQuickPanel: {
    viewFullDetails:  'View full details',
    available:        'Available',
    newReservation:   '+ New reservation',
    walkIn:           'Walk-in',
    locked:           'Locked',
    statusOccupied:   'Occupied',
    statusOverdue:    'Over time',
    statusReserved:   'Reserved',
    hostNote:         'Host note',
    guestNote:        'Guest note',
    labelTime:        'Time',
    labelGuests:      'Guests',
    labelDuration:    'Duration',
    labelSource:      'Source',
    lockedTitle:      'Table locked',
    smsSent:          'SMS sent ✓',
    editCovers:       'Edit covers',
    addNote:          'Add note',
    editNote:         'Edit note',
    saveNote:         'Save',
    cancelEdit:       'Cancel',
    extend15:         'Extend 15 min',
    extend30:         'Extend 30 min',
    unseatConfirm:    'Unseat guest?',
    unseatConfirmYes: 'Yes, unseat',
    arrivalLate:      'Late',
    arrivalNoShowRisk:'No-show risk',
    arrivalDueNow:    'Due now',
    arrivalSoon:      'Arriving soon',
    minOver:          (n: number) => `${n} min over`,
    minLeft:          (n: number) => `${n} min left`,
  },

  // ── BulkConfirmModal ──────────────────────────────────────────────────────
  bulkConfirm: {
    title:            'Send Confirmations',
    targetLabel:      'Sending confirmations for',
    targetToday:      'Today',
    targetTomorrow:   'Tomorrow',
    targetCustom:     'Pick date',
    toggleNextTwo:    'Only next 2 hours',
    totalCount:       (n: number) => `${n} reservation${n === 1 ? '' : 's'} total`,
    eligibleCount:    (n: number) => `${n} guest${n === 1 ? '' : 's'} will receive a message`,
    alreadyConfirmed: (n: number) => `${n} already confirmed by guest`,
    excludedNoPhone:  (n: number) => `${n} no phone`,
    excludedBadStatus:(n: number) => `${n} cancelled / no-show / completed`,
    cooldown:         (n: number) => `${n} sent within last hour`,
    noEligible:       'No eligible guests to message',
    sendButton:       (n: number) => `Send to ${n} guest${n === 1 ? '' : 's'}`,
    sending:          'Sending…',
    loading:          'Loading reservations…',
    fetchError:       'Could not load reservations',
    resultSent:       (n: number) => `✓ ${n} sent`,
    resultFailed:     (n: number) => `✗ ${n} failed`,
    sendError:        'Send failed — please try again',
    close:            'Close',
  },

  // ── CallDrawer ─────────────────────────────────────────────────────────────
  callDrawer: {
    title:           'Incoming Call',
    incomingLabel:   'Incoming call',
    unknownCaller:   'Unknown Caller',
    lookingUp:       'Looking up caller…',
    guestFound:      'Guest on record',
    noGuest:         'No guest record found',
    newReservation:  'New Reservation',
    dismiss:         'Dismiss',
    visits:          (n: number) => `${n} visit${n === 1 ? '' : 's'}`,
    noShows:         (n: number) => `${n} no-show${n === 1 ? '' : 's'}`,
    frequentGuest:   'Regular',
    todayRes:        "Today's reservation",
    openReservation: 'Open reservation',
    lastVisit:       'Last visit',
  },

  // ── LockTableModal ─────────────────────────────────────────────────────────
  lockModal: {
    title:           (name: string) => `Lock ${name}`,
    reasonLabel:     'Reason',
    optional:        '(optional)',
    lockUntilLabel:  'Lock until',
    reasonPh:        'Custom reason…',
    lockButton:      'Lock table',
    lockBusy:        'Locking…',
    cancelButton:    'Cancel',
    errorFailed:     'Failed to lock table',
  },

  // ── LayoutEditor ───────────────────────────────────────────────────────────
  layoutEditor: {
    title:              'Map Editor',
    hint:               'Click · Shift+click to multi-select · Drag to move',
    snapOff:            'Snap: Off',
    snapN:              (n: number) => `Snap: ${n}px`,
    snapTitle:          'Cycle snap grid size',
    saveButton:         'Save map',
    saveBusy:           'Saving…',
    saveSuccess:        'Saved',
    cancelButton:       'Cancel',
    backButton:         '← Back',
    backGo:             '← Go back',
    alignLabel:         'Align',
    distributeLabel:    'Distribute',
    selectedCount:      (n: number) => `${n} selected`,
    clearSelection:     'Clear',
    multiSelected:      (n: number) => `${n} tables selected`,
    multiHint:          'Use alignment tools above · drag any selected table to move all',
    deleteSelected:     'Delete selected',
    // Sidebar
    sectionSections:    'Sections',
    sectionTables:      'Tables',
    sectionFloorObjs:   'Floor Objects',
    floorObjsHint:      'Saved with the map.',
    noSectionsYet:      'No sections yet',
    addSection:         '+ Add section',
    addSectionBtn:      'Add',
    cancelSection:      'Cancel',
    sectionPh:          'e.g. Bar, Terrace',
    addTable:           '+ Add table',
    tagNew:             'new',
    tagOff:             'off',
    occupiedTitle:      'Currently occupied',
    // Bottom panel — single table
    fieldName:          'Name',
    fieldMinCovers:     'Min covers',
    fieldMaxCovers:     'Max covers',
    fieldShape:         'Shape',
    fieldSection:       'Section',
    fieldStatus:        'Status',
    fieldLock:          'Lock',
    noSection:          'No section',
    statusActive:       'Active',
    statusInactive:     'Inactive',
    lockLocked:         'Locked',
    lockUnlocked:       'Unlocked',
    removeField:        'Remove',
    deleteField:        'Delete',
    sizeLabel:          'Size',
    customLabel:        'Custom',
    pxUnit:             'px',
    rotateCW:           'Rotate 90°',
    // Multi-select batch edit
    batchShape:         'Shape',
    batchSection:       'Section',
    batchSize:          'Scale',
    // Floor object panel
    fieldLabel:         'Label',
    fieldW:             'W',
    fieldH:             'H',
    removeObject:       'Remove',
    // Confirm dialog
    confirmOccupiedMove:   'Table is currently occupied. Move anyway?',
    confirmOccupiedEdit:   'Table is currently occupied. Continue?',
    confirmOccupiedDelete: (name: string) => `Cannot delete "${name}" — table is currently occupied.`,
    confirmSuggestion:     'Suggestion:',
    confirmMoveGuests:     'Move guests first',
    confirmMoveGuestsDel:  'Move guests first, then delete.',
    confirmContinue:       'Continue anyway',
    confirmOK:             'OK',
    // Errors
    errorLoad:          'Failed to load map',
    errorSection:       'Failed to save section',
    errorSave:          'Save failed',
    // Floor object type labels
    objWall:           'Wall',
    objDivider:        'Divider',
    objBar:            'Bar',
    objEntrance:       'Entrance',
    objZone:           'Zone',
    objPlanter:        'Planter',
    objHostStand:      'Host Stand',
    objServiceLane:    'Service Lane',
    objLoungeBoundary: 'Lounge Boundary',
    objVipEnclosure:   'VIP Enclosure',
  },

  // ── Flow Control ───────────────────────────────────────────────────────────
  flowControl: {
    pressureHigh:    'High load',
    pressureMed:     'Moderate',
    softHoldTitle:   (name: string) => `Suggested for ${name}`,
    softHoldWaiting: (n: number) => `waiting ${n}m`,
    softHoldSeat:    (name: string) => `Seat ${name}`,
    softHoldIgnore:  'Walk-in instead',
    urgencyHigh:     'Long wait',
    urgencyCritical: 'Very long wait',
    rankLabel:       (n: number) => `#${n}`,
  },

  // ── Smart Seat suggestions ─────────────────────────────────────────────────
  smartSeat: {
    conflictWarn: (n: number) => `Next reservation in ${n}m — seat anyway?`,
    seatAnyway:   'Seat anyway',
  },

  // ── Admin Portal ───────────────────────────────────────────────────────────
  admin: {
    title:                 'Admin Portal',
    logout:                'Sign out',
    restaurants:           'Locations',
    newRestaurant:         '+ Add Location',
    noRestaurants:         'No locations yet',
    noRestaurantsHint:     'Add your first location to get started.',
    createRestaurant:      'Add Location',
    restaurantCreated:     'Location added',
    selectOrCreate:        'Select a location or add a new one',
    settingsSaved:         'Settings saved',
    userCreated:           'User created',
    userUpdated:           'User updated',
    sampleLayoutApplied:   'Sample map applied',
    sampleLayoutConfirm:   'This will delete all existing tables and seed a default map. Continue?',
    sampleLayoutBtn:       'Seed sample map',
    sampleLayoutBusy:      'Seeding…',
    // Wizard
    wizardStep:            (n: number, total: number) => `Step ${n} of ${total}`,
    step1Title:            'Location details',
    step2Title:            'Service settings',
    step3Title:            'First team member',
    wizardNext:            'Next →',
    wizardBack:            '← Back',
    wizardCreate:          'Add location',
    wizardCreateBusy:      'Creating…',
    skipUser:              'Skip — add users later',
    // Fields
    fieldName:             'Location name *',
    fieldSlug:             'URL slug *',
    fieldTimezone:         'Timezone',
    fieldPhone:            'Phone',
    fieldEmail:            'Email',
    fieldAddress:          'Address',
    fieldDefaultTurn:      'Default turn time (min)',
    fieldSlotInterval:     'Slot interval (min)',
    fieldMaxParty:         'Max party size',
    fieldAutoConfirm:      'Auto-confirm reservations',
    fieldBuffer:           'Buffer between turns (min)',
    fieldLastSeating:      'Last seating offset (min)',
    fieldLateThreshold:    'Late threshold (min)',
    fieldNoShowThreshold:  'No-show threshold (min)',
    fieldFirstName:        'First name *',
    fieldLastName:         'Last name *',
    fieldUserEmail:        'Email *',
    fieldPassword:         'Password *',
    fieldRole:             'Role',
    // Detail view
    tabInfo:               'Info',
    tabSettings:           'Settings',
    tabUsers:              'Users',
    colName:               'Name',
    colEmail:              'Email',
    colRole:               'Role',
    colActive:             'Active',
    colLastLogin:          'Last login',
    addUser:               '+ Add user',
    saveBtn:               'Save',
    saveBusy:              'Saving…',
    cancelBtn:             'Cancel',
    editBtn:               'Edit',
    deactivateBtn:         'Deactivate',
    activateBtn:           'Activate',
    neverLoggedIn:         'Never',
    users:                 (n: number) => `${n} users`,
    tables:                (n: number) => `${n} tables`,
    reservations:          (n: number) => `${n} reservations`,
    // Groups (SUPER_ADMIN only)
    groups:                'Groups',
    newGroup:              '+ Create Group',
    noGroups:              'No groups yet',
    noGroupsHint:          'Create a group to manage multiple locations together.',
    groupCreated:          'Group created',
    groupUpdated:          'Group updated',
    groupName:             'Group name *',
    groupSlug:             'URL slug *',
    groupMembers:          'Locations in this group',
    groupAdmins:           'HQ Admins',
    addToGroup:            'Add to group',
    removeFromGroup:       'Remove from group',
    assignLocation:        'Assign location',
    unassigned:            'Unassigned',
    createHqUser:          '+ Add HQ Admin',
    hqAdminCreated:        'HQ Admin created',
    noHqAdmins:            'No HQ admins yet',
    // Setup page
    setupTitle:            'Welcome to Iron Booking',
    setupSubtitle:         'Create your super admin account to get started.',
    setupSubmit:           'Create account',
    setupSubmitBusy:       'Creating…',
  },

  // ── Service Report ─────────────────────────────────────────────────────────
  serviceReport: {
    title:               'Service Report',
    close:               'Close',
    tabAll:              'All Day',
    tabLunch:            'Lunch',
    tabDinner:           'Dinner',
    loading:             'Loading…',
    error:               'Failed to load report',
    retry:               'Retry',
    noData:              'No reservations for this date',
    lunchShift:          (from: string, to: string) => `Lunch · ${from}–${to}`,
    dinnerShift:         (from: string) => `Dinner · ${from}+`,
    labelReservations:   'Reservations',
    labelExpectedGuests: 'Expected Guests',
    labelSeated:         'Seated',
    labelCompleted:      'Completed',
    labelNoShows:        'No-shows',
    labelCancelled:      'Cancelled',
    labelPending:        'Pending',
    labelConfirmed:      'Confirmed',
    labelWalkIns:        'Walk-ins',
    labelPhone:          'Phone bookings',
    labelOnline:         'Online / OT / Resy',
    labelNoShowPct:      'No-show rate',
    labelCancellationPct:'Cancellation rate',
    guests:              (n: number) => `${n}`,
    pct:                 (n: number) => `${n}%`,
  },

  // ── Host Selection Screen ─────────────────────────────────────────────────
  hostSelection: {
    title:          'Who is working today?',
    subtitle:       'Tap your name to sign in',
    noHosts:        'No hosts configured yet',
    noHostsHint:    'A manager must add hosts in Settings → Hosts first.',
    managerLogin:   'Manager Login',
    pinTitle:       (name: string) => `Enter PIN for ${name}`,
    pinBack:        'Back',
    pinError:       'Incorrect PIN — try again',
    pinSubmitting:  'Signing in…',
    loadError:      'Failed to load hosts',
    roleHost:       'Host',
    roleServer:     'Server',
    roleManager:    'Manager',
  },

  // ── Hosts Settings ────────────────────────────────────────────────────────
  hostsSettings: {
    title:          'Hosts',
    back:           '← Back',
    addHost:        '+ Add Host',
    noHosts:        'No hosts yet',
    noHostsHint:    'Add floor staff who log in with a PIN.',
    roleLabel:      'Role',
    roleHost:       'Host',
    roleServer:     'Server',
    roleManager:    'Manager',
    pinSet:         'PIN set',
    pinNotSet:      'No PIN',
    setPin:         'Set PIN',
    changePin:      'Change PIN',
    editBtn:        'Edit',
    deactivate:     'Deactivate',
    activate:       'Activate',
    deleteBtn:      'Delete',
    deleteConfirm:  (name: string) => `Delete ${name}? This cannot be undone.`,
    // Create / edit form
    formTitleCreate:'New Host',
    formTitleEdit:  'Edit Host',
    fieldFirst:     'First name',
    fieldLast:      'Last name',
    fieldAvatar:    'Avatar URL (optional)',
    fieldRole:      'Role',
    saveBtn:        'Save',
    saveBusy:       'Saving…',
    cancelBtn:      'Cancel',
    // PIN dialog
    pinDialogTitle: (name: string) => `Set PIN for ${name}`,
    pinHint:        'Enter a 4-digit PIN',
    pinConfirmHint: 'Confirm PIN',
    pinMismatch:    'PINs do not match',
    pinSaveBtn:     'Save PIN',
    pinSaveBusy:    'Saving…',
    pinCancelBtn:   'Cancel',
    // Toasts
    toastCreated:   (name: string) => `${name} added`,
    toastUpdated:   (name: string) => `${name} updated`,
    toastPinSet:    (name: string) => `PIN set for ${name}`,
    toastToggled:   (name: string, active: boolean) => `${name} ${active ? 'activated' : 'deactivated'}`,
    toastDeleted:   (name: string) => `${name} deleted`,
    toastError:       'Something went wrong',
    permissionDenied: 'Manager permission required',
    permissionHint:   'Only managers and owners can manage hosts.',
  },

  // ── HostDashboard ──────────────────────────────────────────────────────────
  hostDashboard: {
    editLayout:       'Edit Map',
    combineTables:    'Combine tables',
    cancelCombine:    'Cancel',
    toastSeated:      'Guest seated',
    toastCreated:     'Reservation created',
    toastUnlocked:    'Table unlocked',
    toastUnlockFail:  'Failed to unlock table',
    toastWLRemoved:   'Removed from waitlist',
    toastWLRemoveFail:'Failed to remove',
    toastNoShow:      'Marked as no-show',
    toastNoShowFail:  'Failed',
    toastSeatFail:    'Failed to seat guest',
    toastNoTable:     'Select a table before seating',
    toastSeatAt:        (name: string, table: string) => `${name} seated at ${table}`,
    toastNotified:      (name: string) => `WhatsApp sent to ${name}`,
    toastNotifyFail:    'Failed to send WhatsApp',
    toastQuickSeated:    (table: string) => `Guest seated at ${table}`,
    toastQuickUndone:    'Reservation reverted',
    toastUndoFail:       'Failed to undo',
    quickSeatUndo:       'Undo',
    reorganizeFloor:     'Reorganize Floor',
    exitReorganize:      'Exit Reorganize',
    rebuildDayTitle:     (table: string) => `Lift reservations from ${table}`,
    rebuildDayBody:      (n: number) => `${n} upcoming ${n === 1 ? 'reservation' : 'reservations'} will be moved to the Reorganize queue for re-assignment.`,
    rebuildDayNoRes:     'No upcoming reservations to lift from this table.',
    rebuildDayReason:    'Reason (optional)',
    rebuildDayConfirm:   'Lift Reservations',
    toastRebuildDone:    (n: number, table: string) => `${n} ${n === 1 ? 'reservation' : 'reservations'} lifted from ${table}`,
    toastRebuildFail:    'Failed to lift reservations',
    toastCancelFail:     'Failed to cancel',
    serviceReportBtn:    'Service Report',
    hostsBtn:            'Hosts',
    activityLogBtn:      'Activity Log',
  },

  // ── Activity Log ────────────────────────────────────────────────────────────
  activityLog: {
    title:        'Activity Log',
    backButton:   '← Back',
    filterDate:   'Date',
    filterHost:   'Host',
    filterAction: 'Action',
    allHosts:     'All hosts',
    allActions:   'All actions',
    empty:        'No activity found for this date.',
    loading:      'Loading…',
    loadMore:     'Load more',
    totalEntries: 'entries',
    loadError:    'Failed to load activity log',
    actions: {
      CREATED:              'Created',
      UPDATED:              'Updated',
      CONFIRMED:            'Confirmed',
      REVERTED_TO_PENDING:  'Reverted',
      SEATED:               'Seated',
      MOVED:                'Moved',
      TABLE_ASSIGNED:       'Table assigned',
      TABLE_MOVED:          'Table changed',
      COMPLETED:            'Completed',
      CANCELLED:            'Cancelled',
      NO_SHOW:              'No-show',
      RETURN_TO_LIST:       'Returned to list',
      REORGANIZE_TRIGGERED: 'Reorganized',
      REORGANIZE_RESOLVED:  'Reorganize resolved',
    } as Record<string, string>,
  },
};
