// All user-visible strings in English.
// To add a locale, create a parallel object with the same shape and swap T at app init.

export const T = {

  // ── Shared ─────────────────────────────────────────────────────────────────
  common: {
    cancel:     'Cancel',
    back:       '← Back',
    ok:         'OK',
    add:        'Add',
    remove:     'Remove',
    delete:     'Delete',
    unlock:     'Unlock',
    none:       'None',
    vip:        'VIP',
    processing: 'Processing…',
    guests:     (n: number) => `${n} guests`,
    nMin:       (n: number) => `${n} min`,
  },

  // ── Reservation status labels ───────────────────────────────────────────────
  reservationStatus: {
    PENDING:   'Pending',
    CONFIRMED: 'Confirmed',
    SEATED:    'Seated',
    COMPLETED: 'Completed',
    CANCELLED: 'Cancelled',
    NO_SHOW:   'No-show',
  } as Record<string, string>,

  // ── Live table status labels ────────────────────────────────────────────────
  tableStatus: {
    AVAILABLE:     'Available',
    OCCUPIED:      'Seated',
    RESERVED_SOON: 'Arriving soon',
    RESERVED:      'Reserved',
    BLOCKED:       'Blocked',
  } as Record<string, string>,

  // ── TopBar ─────────────────────────────────────────────────────────────────
  topBar: {
    brand:          'Iron Booking',
    zoomTitle:      'Zoom — click percentage to reset to 100%',
    zoomOut:        'Zoom out',
    zoomIn:         'Zoom in',
    resetZoom:      'Reset to 100%',
    switchToLight:  'Switch to light mode',
    switchToDark:   'Switch to dark mode',
    signOut:        'Sign out',
    prevDay:        'Previous day',
    nextDay:        'Next day',
    prev15:         '−15m',
    next15:         '+15m',
    nowBtn:         'Now',
  },

  // ── FloorBoard ─────────────────────────────────────────────────────────────
  floorBoard: {
    errorTitle:       'Cannot reach server',
    errorHint:        'Check the backend is reachable at iron-booking.onrender.com.',
    errorRetry:       'Dashboard will retry automatically.',
    emptyTitle:       'No tables configured',
    emptyHint:        'Add tables via the admin panel, then refresh.',
    statAvailable:    'Available',
    statSeated:       'Seated',
    statArriving:     'Arriving',
    statReserved:     'Reserved',
    tableCount:       (n: number) => `${n} tables`,
    lockedTitle:      (name: string) => `${name} is locked`,
    unlockTable:      'Unlock table',
    lockTable:        'Lock table…',
    seatAnyway:       'Seat walk-in anyway',
    ending:           'Ending',
    mLeft:            (n: number) => `${n}m left`,
    mOver:            (n: number) => `+${n}m over`,
    inNMin:           (n: number) => `in ${n}m`,
    viewFloor:        'Floor',
    viewTimeline:     'Timeline',
  },

  // ── TableCard ──────────────────────────────────────────────────────────────
  tableCard: {
    clickToSeat:     'Click to seat a walk-in',
    openTapToSeat:   'Open · tap to seat walk-in',
    endsIn:          (n: number) => `Ends in ${n}m`,
    endsNow:         'Ends now',
    overBy:          (n: number) => `Over by ${n}m`,
    lateBy:          (n: number) => `${n}m late`,
    inNMin:          (n: number) => `in ${n}m`,
    waitlistWaiting: (n: number) => `Waitlist · ${n}m waiting`,
    locked:          'Locked',
  },

  // ── ActionBar ──────────────────────────────────────────────────────────────
  actionBar: {
    now: 'Now',
  },

  // ── Arrival states ─────────────────────────────────────────────────────────
  arrival: {
    arrivingSoon:  'Arriving soon',
    dueNow:        'Due now',
    lateMin:       (n: number) => `${n}m late`,
    noShowRisk:    'No-show risk',
    insightLate:   (name: string, n: number) => `${name} is ${n}m late`,
    insightNoShow: (name: string, n: number) => `${name} — no-show risk (${n}m)`,
  },

  // ── ReservationPanel ───────────────────────────────────────────────────────
  reservationPanel: {
    tabReservations:  'Reservations',
    tabWaitlist:      'Waitlist',
    walkIn:           'Walk-in',
    newReservation:   '+ New',
    searchPlaceholder:'Search guest name…',
    filterAll:        'All',
    filterPending:    'Pending',
    filterConfirmed:  'Confirmed',
    filterSeated:     'Seated',
    filterDone:       'Done',
    emptyTitle:       'No reservations today',
    emptyHintNew:     '+ New',
    emptyHintWalkIn:  'Walk-in',
    emptyHint:        'Use {new} for a phone booking or {walkIn} for guests at the door.',
    emptyFiltered:    'No reservations match this filter',
    showing:          (visible: number, total: number) => `Showing ${visible} of ${total}`,
  },

  // ── WaitlistPanel ──────────────────────────────────────────────────────────
  waitlistPanel: {
    readyToSeat:      'Ready to seat',
    seatButton:       'Seat',
    namePlaceholder:  'Guest name *',
    partyPlaceholder: 'Party *',
    phonePlaceholder: 'Phone (optional)',
    addButton:        'Add to waitlist',
    addBusy:          'Adding…',
    addLink:          '+ Add guest to waitlist',
    emptyTitle:       'Waitlist is empty',
    emptyHint:        'Add guests above when all tables are occupied.',
    noShow:           'No-show',
    cancelButton:     'Cancel',
    footerEmpty:      'No one waiting',
    footerCount:      (n: number) => `${n} waiting`,
    mWaiting:         (n: number) => `${n}m waiting`,
    guests:           (n: number) => `${n} guests`,
    tableLabel:       (name: string) => `Table ${name}`,
    etaReady:         'Ready now',
    etaMin:           (n: number) => `ETA ${n}m`,
    waitingMin:       (n: number) => `waiting ${n}m`,
    justAdded:        'Just added',
  },

  // ── CreateDrawer ───────────────────────────────────────────────────────────
  createDrawer: {
    titleReservation:     'New Reservation',
    titleWalkIn:          'Walk-in',
    tabReservation:       'Reservation',
    tabWalkIn:            'Walk-in',
    // Reservation form
    fieldGuestName:       'Guest name *',
    fieldPhone:           'Phone',
    fieldPartySize:       'Party size *',
    fieldDate:            'Date *',
    fieldTime:            'Time *',
    fieldDuration:        'Duration (min)',
    fieldSource:          'Source',
    fieldGuestNotes:      'Guest notes',
    fieldHostNotes:       'Host notes',
    fieldTable:           'Assign table (optional)',
    placeholderName:      'Full name',
    placeholderPhone:     '+1 555 000 0000',
    placeholderDuration:  '90',
    placeholderGuestNotes:'Allergies, special requests…',
    placeholderHostNotes: 'Internal notes for the team…',
    sourcePhone:          'Phone',
    sourceInternal:       'Internal',
    submitCreate:         'Create & Confirm',
    submitCreateBusy:     'Creating…',
    tableNone:            'None',
    // Walk-in form
    fieldWalkInName:      'Guest name',
    fieldWalkInParty:     'Party size *',
    fieldWalkInNotes:     'Notes',
    fieldWalkInTable:     'Table (select to seat immediately)',
    placeholderWalkInName:"Optional — defaults to 'Walk-in Guest'",
    placeholderWalkInNotes:'Allergies, occasion, preferences…',
    walkInTableSelected:  (name: string) => `Table ${name} selected — guest will be seated immediately.`,
    walkInNoTable:        'No table selected — guest will be added to the confirmed list.',
    submitSeatNow:        'Seat Now',
    submitSeatNowBusy:    'Seating…',
    submitAddToList:      'Add to List',
    submitAddToListBusy:  'Adding…',
  },

  // ── GuestDrawer ────────────────────────────────────────────────────────────
  guestDrawer: {
    editButton:           'Edit',
    // Reservation detail rows
    rowDate:              'Date',
    rowTime:              'Time',
    rowDuration:          'Duration',
    rowTable:             'Table',
    rowSource:            'Source',
    rowOccasion:          'Occasion',
    rowGuestNotes:        'Guest notes',
    rowHostNotes:         'Host notes',
    tableUnassigned:      'Unassigned',
    durationValue:        (n: number) => `${n} min`,
    // Guest profile
    sectionGuestProfile:  'Guest profile',
    rowName:              'Name',
    rowVisits:            'Visits',
    rowNoShows:           'No-shows',
    // Actions
    sectionActions:       'Actions',
    actionConfirm:        'Confirm',
    actionSeat:           'Seat',
    actionNoShow:         'No-show',
    actionCancel:         'Cancel',
    actionComplete:       'Complete',
    actionMoveTable:      'Move table',
    actionUndo:           'Undo',
    // Edit mode fields
    fieldGuestName:       'Guest name',
    fieldPhone:           'Phone',
    fieldPartySize:       'Party size',
    fieldDuration:        'Duration',
    fieldGuestNotes:      'Guest notes',
    fieldHostNotes:       'Host notes',
    placeholderName:      'Full name',
    placeholderPhone:     '+1 555 000 0000',
    placeholderNotes:     'Allergies, preferences…',
    placeholderHostNotes: 'Internal notes…',
    placeholderMinutes:   'Minutes',
    wasNMin:              (n: number) => `was ${n}m`,
    saveChanges:          'Save changes',
    // Seat / move pickers
    seatPickerLabel:      'Select a table to seat:',
    movePickerLabel:      'Move to table:',
    noTablesAvailable:    'No tables available',
    backLink:             '← Back',
    // Cancel mode
    cancelReasonLabel:    'Reason (optional):',
    cancelReasonPh:       'Guest request, weather…',
    confirmCancel:        'Confirm cancel',
    backButton:           'Back',
    // Table lock section
    sectionTableLock:     'Table lock',
    unlockButton:         'Unlock',
    lockTableButton:      'Lock table…',
    lockTableBusy:        'Locking…',
    lockTableConfirm:     'Lock table',
    lockReasonPh:         'Custom reason (optional)',
    quickLockReasons:     ['VIP', 'Broken', 'Staff', 'Reserved', 'Other'] as const,
    // Timeline section
    sectionTimeline:      'Timeline',
    timelineEmpty:        'No lifecycle events yet',
    tsConfirmed:          'Confirmed',
    tsSeated:             'Seated',
    tsCompleted:          'Completed',
    tsCancelled:          'Cancelled',
    tsNoShow:             'No-show',
    // Toasts
    toastUpdated:         'Reservation updated',
    toastConfirmed:       'Reservation confirmed',
    toastNoShow:          'Marked as no-show',
    toastCompleted:       'Reservation completed',
    toastUndone:          'Action undone',
    toastSeated:          (table: string) => `Seated at ${table}`,
    toastMoved:           (table: string) => `Moved to ${table}`,
    toastLocked:          (name: string) => `${name} locked`,
    toastUnlocked:        (name: string) => `${name} unlocked`,
    // Fallback error
    actionFailed:         'Action failed',
  },

  // ── LockTableModal ─────────────────────────────────────────────────────────
  lockModal: {
    title:           (name: string) => `Lock ${name}`,
    reasonLabel:     'Reason',
    optional:        '(optional)',
    lockUntilLabel:  'Lock until',
    reasonPh:        'Custom reason…',
    lockButton:      'Lock table',
    lockBusy:        'Locking…',
    cancelButton:    'Cancel',
    errorFailed:     'Failed to lock table',
  },

  // ── LayoutEditor ───────────────────────────────────────────────────────────
  layoutEditor: {
    title:              'Floor Plan Builder',
    hint:               'Click · Shift+click to multi-select · Drag to move',
    snapOff:            'Snap: Off',
    snapN:              (n: number) => `Snap: ${n}px`,
    snapTitle:          'Cycle snap grid size',
    saveButton:         'Save layout',
    saveBusy:           'Saving…',
    cancelButton:       'Cancel',
    backButton:         '← Back',
    backGo:             '← Go back',
    alignLabel:         'Align',
    distributeLabel:    'Distribute',
    selectedCount:      (n: number) => `${n} selected`,
    clearSelection:     'Clear',
    multiSelected:      (n: number) => `${n} tables selected`,
    multiHint:          'Use alignment tools above · drag any selected table to move all',
    deleteSelected:     'Delete selected',
    // Sidebar
    sectionSections:    'Sections',
    sectionTables:      'Tables',
    sectionFloorObjs:   'Floor Objects',
    floorObjsHint:      'Saved to database with layout.',
    noSectionsYet:      'No sections yet',
    addSection:         '+ Add section',
    addSectionBtn:      'Add',
    cancelSection:      'Cancel',
    sectionPh:          'e.g. Bar, Terrace',
    addTable:           '+ Add table',
    tagNew:             'new',
    tagOff:             'off',
    occupiedTitle:      'Currently occupied',
    // Bottom panel — single table
    fieldName:          'Name',
    fieldMinCovers:     'Min covers',
    fieldMaxCovers:     'Max covers',
    fieldShape:         'Shape',
    fieldSection:       'Section',
    fieldStatus:        'Status',
    fieldLock:          'Lock',
    noSection:          'No section',
    statusActive:       'Active',
    statusInactive:     'Inactive',
    lockLocked:         'Locked',
    lockUnlocked:       'Unlocked',
    removeField:        'Remove',
    deleteField:        'Delete',
    sizeLabel:          'Size',
    customLabel:        'Custom',
    pxUnit:             'px',
    // Floor object panel
    fieldLabel:         'Label',
    fieldW:             'W',
    fieldH:             'H',
    removeObject:       'Remove',
    // Confirm dialog
    confirmOccupiedMove:   'Table is currently occupied. Move anyway?',
    confirmOccupiedEdit:   'Table is currently occupied. Continue?',
    confirmOccupiedDelete: (name: string) => `Cannot delete "${name}" — table is currently occupied.`,
    confirmSuggestion:     'Suggestion:',
    confirmMoveGuests:     'Move guests first',
    confirmMoveGuestsDel:  'Move guests first, then delete.',
    confirmContinue:       'Continue anyway',
    confirmOK:             'OK',
    // Errors
    errorLoad:          'Failed to load layout',
    errorSection:       'Failed to save section',
    errorSave:          'Save failed',
  },

  // ── Flow Control ───────────────────────────────────────────────────────────
  flowControl: {
    pressureHigh:    'High load',
    pressureMed:     'Moderate',
    softHoldTitle:   (name: string) => `Suggested for ${name}`,
    softHoldWaiting: (n: number) => `waiting ${n}m`,
    softHoldSeat:    (name: string) => `Seat ${name}`,
    softHoldIgnore:  'Walk-in instead',
    urgencyHigh:     'Long wait',
    urgencyCritical: 'Very long wait',
    rankLabel:       (n: number) => `#${n}`,
  },

  // ── Smart Seat suggestions ─────────────────────────────────────────────────
  smartSeat: {
    conflictWarn: (n: number) => `Next reservation in ${n}m — seat anyway?`,
    seatAnyway:   'Seat anyway',
  },

  // ── Admin Portal ───────────────────────────────────────────────────────────
  admin: {
    title:                 'Admin Portal',
    logout:                'Sign out',
    restaurants:           'Restaurants',
    newRestaurant:         '+ New Restaurant',
    noRestaurants:         'No restaurants yet',
    noRestaurantsHint:     'Create your first restaurant to get started.',
    createRestaurant:      'Create Restaurant',
    restaurantCreated:     'Restaurant created',
    settingsSaved:         'Settings saved',
    userCreated:           'User created',
    userUpdated:           'User updated',
    sampleLayoutApplied:   'Sample layout applied',
    sampleLayoutConfirm:   'This will delete all existing tables and seed a default layout. Continue?',
    sampleLayoutBtn:       'Seed sample layout',
    sampleLayoutBusy:      'Seeding…',
    // Wizard
    wizardStep:            (n: number, total: number) => `Step ${n} of ${total}`,
    step1Title:            'Restaurant details',
    step2Title:            'Service settings',
    step3Title:            'First team member',
    wizardNext:            'Next →',
    wizardBack:            '← Back',
    wizardCreate:          'Create restaurant',
    wizardCreateBusy:      'Creating…',
    skipUser:              'Skip — add users later',
    // Fields
    fieldName:             'Restaurant name *',
    fieldSlug:             'URL slug *',
    fieldTimezone:         'Timezone',
    fieldPhone:            'Phone',
    fieldEmail:            'Email',
    fieldAddress:          'Address',
    fieldDefaultTurn:      'Default turn time (min)',
    fieldSlotInterval:     'Slot interval (min)',
    fieldMaxParty:         'Max party size',
    fieldAutoConfirm:      'Auto-confirm reservations',
    fieldBuffer:           'Buffer between turns (min)',
    fieldLastSeating:      'Last seating offset (min)',
    fieldLateThreshold:    'Late threshold (min)',
    fieldNoShowThreshold:  'No-show threshold (min)',
    fieldFirstName:        'First name *',
    fieldLastName:         'Last name *',
    fieldUserEmail:        'Email *',
    fieldPassword:         'Password *',
    fieldRole:             'Role',
    // Detail view
    tabInfo:               'Info',
    tabSettings:           'Settings',
    tabUsers:              'Users',
    colName:               'Name',
    colEmail:              'Email',
    colRole:               'Role',
    colActive:             'Active',
    colLastLogin:          'Last login',
    addUser:               '+ Add user',
    saveBtn:               'Save',
    saveBusy:              'Saving…',
    cancelBtn:             'Cancel',
    editBtn:               'Edit',
    deactivateBtn:         'Deactivate',
    activateBtn:           'Activate',
    neverLoggedIn:         'Never',
    users:                 (n: number) => `${n} users`,
    tables:                (n: number) => `${n} tables`,
    reservations:          (n: number) => `${n} reservations`,
    // Setup page
    setupTitle:            'Welcome to Iron Booking',
    setupSubtitle:         'Create your super admin account to get started.',
    setupSubmit:           'Create account',
    setupSubmitBusy:       'Creating…',
  },

  // ── HostDashboard ──────────────────────────────────────────────────────────
  hostDashboard: {
    editLayout:       'Edit Layout',
    toastSeated:      'Guest seated',
    toastCreated:     'Reservation created',
    toastUnlocked:    'Table unlocked',
    toastUnlockFail:  'Failed to unlock table',
    toastWLRemoved:   'Removed from waitlist',
    toastWLRemoveFail:'Failed to remove',
    toastNoShow:      'Marked as no-show',
    toastNoShowFail:  'Failed',
    toastSeatFail:    'Failed to seat guest',
    toastSeatAt:      (name: string, table: string) => `${name} seated at ${table}`,
  },
};
